import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import { Navigator } from "@/components/navigator/Navigator";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { Audioplayer } from "@/components/audioplayer/Audioplayer";
import { useAppSelector } from "@/store/store";
import { ClientComponent } from "@/components/clientComponentAudioplayer/ClientComponentAudioplayer";
import { ContentTitle } from "@/components/centerblock/Centerblock";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <ReduxProvider>
        <body className={inter.className}>
          <div className="wrapper">
            <div className="contaner">
              <div className="main">
                <Navigator />
                {children}
                <Sidebar />
                <div className="audioplayer">
                  <ClientComponent />
                </div>
              </div>
            </div>
          </div>
        </body>
      </ReduxProvider>
    </html>
  );
}
